# Generated by Django 4.2.4 on 2023-09-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0004_usuario_clientes_usuario_empresas_terceiras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='funcionarios',
            field=models.IntegerField(default=0),
        ),
    ]
